export const basics = [
  {
    name: "Create React App",
    index: 1,
    status: "Done",
    x: "-100%",
    y: "10vh"
  },
  {
    name: "JSX",
    index: 2,
    status: "Done",
    x: "-100%",
    y: "15vh",
  },
  {
    name: "Components",
    index: 3,
    status: "Done",
    x: "-100%",
    y: "20vh",
  },
  {
    name: "Props vs State",
    index: 4,
    status: "Done",
    x: "-100%",
    y: "25vh",
  },
  {
    name: "Conditional Rendering",
    index: 5,
    status: "Done",
    x: "-100%",
    y: "30vh",
  },
  {
    name: "Functional Components",
    index: 6,
    status: "Done",
    x: "-215%",
    y: "17.8vh",
  },
  {
    name: "Class Components",
    index: 7,
    status: "Done",
    x: "-215%",
    y: "22.2vh",
  },
  {
    name: "Component Life Cycle",
    index: 8,
    status: "Done",
    x: "100%",
    y: "10vh",
  },
  {
    name: "Lists and Keys",
    index: 9,
    status: "Done",
    x: "100%",
    y: "15vh",
  },
  {
    name: "Composition & Inheritance",
    index: 10,
    status: "Done",
    x: "100%",
    y: "20vh",
  },
  {
    name: "Basic Hooks",
    index: 11,
    status: "Done",
    x: "100%",
    y: "25vh",
  },
  {
    name: "useState",
    index: 12,
    status: "Done",
    x: "95%",
    y: "30vh",
  },
  {
    name: "useEffect",
    index: 13,
    status: "Done",
    x: "205%",
    y: "30vh",
  }
];

export const advanced = [
  {
    name: "Hooks",
    index: 14,
    status: "Done",
    x: "-100%",
    y: "90vh",
  },
  {
    name: "Context",
    index: 15,
    status: "Done",
    x: "-100%",
    y: "95vh",
  },
  {
    name: "Refs",
    index: 16,
    status: "Done",
    x: "-100%",
    y: "100vh",
  },
  {
    name: "Render Props",
    index: 17,
    status: "Done",
    x: "-100%",
    y: "105vh",
  },
  {
    name: "Code Spliting",
    index: 18,
    status: "Done",
    x: "-100%",
    y: "110vh",
  },
  {
    name: "Writing Own Hooks",
    index: 19,
    status: "Done",
    x: "-215%",
    y: "88vh",
  },
  {
    name: "useCallback",
    index: 20,
    status: "Done",
    x: "-215%",
    y: "92vh",
  },
  {
    name: "useRef",
    index: 21,
    status: "Done",
    x: "-215%",
    y: "96vh",
  },
  {
    name: "useMemo",
    index: 22,
    status: "Done",
    x: "-215%",
    y: "100vh",
  },
  {
    name: "useReducer",
    index: 23,
    status: "Done",
    x: "-215%",
    y: "104vh",
  },
  {
    name: "useContext",
    index: 24,
    status: "Done",
    x: "-215%",
    y: "108vh",
  },
  {
    name: "High Order Components",
    index: 25,
    status: "Done",
    x: "100%",
    y: "90vh",
  },
  {
    name: "Portals",
    index: 26,
    status: "Done",
    x: "100%",
    y: "95vh",
  },
  {
    name: "Error Boundaries",
    index: 27,
    status: "Done",
    x: "100%",
    y: "100vh",
  },
  {
    name: "Fiber Architecture",
    index: 28,
    status: "Done",
    x: "100%",
    y: "105vh",
  },
];

export const ecosys = [
  {
    name: "Routers",
    index: 29,
    status: "Done",
    x: "-100%",
    y: "127vh",
  },
  {
    name: "SSR",
    index: 30,
    status: "Done",
    x: "-100%",
    y: "135vh",
  },
  {
    name: "SSG",
    index: 31,
    status: "Pending",
    x: "-100%",
    y: "139vh",
  },
  {
    name: "React Router",
    index: 32,
    status: "Done",
    x: "-215%",
    y: "125vh",
  },
  {
    name: "Reach Router",
    index: 33,
    status: "Todo",
    x: "-215%",
    y: "129vh",
  },
  {
    name: "Next.js",
    index: 34,
    status: "Done",
    x: "-215%",
    y: "135vh",
  },
  {
    name: "Gatsby",
    index: 35,
    status: "Todo",
    x: "-215%",
    y: "139vh",
  },
  {
    name: "API Calls",
    index: 36,
    status: "Pending",
    x: "-100%",
    y: "153vh",
  },
  {
    name: "Apollo",
    index: 37,
    status: "Pending",
    x: "-215%",
    y: "147vh",
  },
  {
    name: "Relay Modern",
    index: 38,
    status: "Todo",
    x: "-215%",
    y: "151vh",
  },
  {
    name: "Axios",
    index: 39,
    status: "Done",
    x: "-215%",
    y: "156vh",
  },
  {
    name: "Unfetch",
    index: 40,
    status: "Todo",
    x: "-215%",
    y: "160vh",
  },
  {
    name: "Superagent",
    index: 41,
    status: "Todo",
    x: "-215%",
    y: "164vh",
  },
  {
    name: "use-http",
    index: 42,
    status: "Todo",
    x: "-100%",
    y: "162vh",
  },
  {
    name: "Mobile",
    index: 43,
    status: "Pending",
    x: "-100%",
    y: "172vh",
  },
  {
    name: "React Native",
    index: 44,
    status: "Pending",
    x: "-215%",
    y: "172vh",
  },
  {
    name: "Forms",
    index: 45,
    status: "Pending",
    x: "100%",
    y: "125vh",
  },
  {
    name: "React Hook Form",
    index: 46,
    status: "Done",
    x: "215%",
    y: "122vh",
  },
  {
    name: "Formik",
    index: 47,
    status: "Todo",
    x: "215%",
    y: "126vh",
  },
  {
    name: "Final Form",
    index: 48,
    status: "Todo",
    x: "215%",
    y: "130vh",
  },
  {
    name: "Testing",
    index: 49,
    status: "Pending",
    x: "100%",
    y: "140vh",
  },
  {
    name: "Jest",
    index: 50,
    status: "Pending",
    x: "215%",
    y: "136vh",
  },
  {
    name: "React Testing Library",
    index: 51,
    status: "Pending",
    x: "215%",
    y: "140vh",
  },
  {
    name: "Cypress",
    index: 52,
    status: "Todo",
    x: "215%",
    y: "144vh",
  },
  {
    name: "State Management",
    index: 53,
    status: "Done",
    x: "100%",
    y: "154vh",
  },
  {
    name: "Context/State",
    index: 54,
    status: "Done",
    x: "215%",
    y: "150vh",
  },
  {
    name: "Redux",
    index: 55,
    status: "Done",
    x: "215%",
    y: "154vh",
  },
  {
    name: "MobX",
    index: 56,
    status: "Todo",
    x: "215%",
    y: "158vh",
  },
  {
    name: "Styling",
    index: 57,
    status: "Done",
    x: "100%",
    y: "168vh",
  },
  {
    name: "Styled Components",
    index: 58,
    status: "Done",
    x: "215%",
    y: "164vh",
  },
  {
    name: "Emotion",
    index: 59,
    status: "Done",
    x: "215%",
    y: "168vh",
  },
  {
    name: "Chakra UI",
    index: 60,
    status: "Todo",
    x: "215%",
    y: "172vh",
  },
  {
    name: "Material UI",
    index: 61,
    status: "Done",
    x: "215%",
    y: "176vh",
  },
  {
    name: "Ant Design",
    index: 62,
    status: "Todo",
    x: "215%",
    y: "180vh",
  },

  
];

// PATRON
// {
//   name: "",
//   index: ,
//   status: "",
//   x: "",
//   y: "",
// },